#!/bin/bash
export BITCOIND_RPC_USER="$APP_BITCOIN_RPC_USER"
export BITCOIND_RPC_PASSWORD="$APP_BITCOIN_RPC_PASS"
export BITCOIND_HOST="$APP_BITCOIN_NODE_IP"
export BITCOIND_PORT="$APP_BITCOIN_RPC_PORT"
