version: "3.7"

services:
  ckpool:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./ckpool.conf:/app/ckpool.conf
    command: ["/ckpool/ckpool", "-c", "/app/ckpool.conf"]
    restart: unless-stopped
