# remove the "version:" key (deprecated)
services:
  belani-ckpool:                # (must match your app id)
    build: .
    working_dir: /ckpool
    command: ["ckpool", "-c", "/ckpool/src/ckpool.conf", "-k", "-q"]
    volumes:
      - ./ckpool.conf:/ckpool/src/ckpool.conf:ro   # ← mount config where the cmd expects it
      - ${APP_DATA_DIR:-/home/umbrel/umbrel/app-data/belani-ckpool}/data:/data
    networks:
      - app_net
    restart: on-failure
    healthcheck:
      test: ["CMD", "true"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app_net:
    external: true
    name: app_proxy
