version: "3.7"
services:
  ckpool:
    build: .
    restart: on-failure
    command: ./pool/ckpool -c pool/ckpool.conf -k -q
    volumes:
      - ${APP_DATA_DIR}/data:/data
    networks:
      - app_net

networks:
  app_net:
    external: true
    name: app_proxy
